POST http://localhost:5000/auth/token
Content-Type: application/json

{
    "clientId": "abc",
    "clientSecret": "123"
}

###

POST http://localhost:5000/auth/addUpdateApiClient
Content-Type: application/json

{
    "clientId": "abc",
    "clientSecret": "123"
}